//
//  CountryNames.swift
//  GuessTheFlag
//
//  Created by İlker Memişoğlu on 30.08.2025.
//

import Foundation

struct Country {
    
   static let names: [String: String] =
     [
      "ad": "Andorra",
      "ae": "Birleşik Arap Emirlikleri",
      "af": "Afganistan",
      "ag": "Antigua ve Barbuda",
      "al": "Arnavutluk",
      "am": "Ermenistan",
      "ao": "Angola",
      "aq": "Antarktika",
      "ar": "Arjantin",
      "at": "Avusturya",
      "au": "Avustralya",
      "az": "Azerbaycan",
      "ba": "Bosna-Hersek",
      "bb": "Barbados",
      "bd": "Bangladeş",
      "be": "Belçika",
      "bf": "Burkina Faso",
      "bg": "Bulgaristan",
      "bh": "Bahreyn",
      "bi": "Burundi",
      "bj": "Benin",
      "bl": "Saint Barthélemy",
      "bm": "Bermuda",
      "bn": "Brunei",
      "bo": "Bolivya",
      "bq": "Karayip Hollandası",
      "br": "Brezilya",
      "bs": "Bahamalar",
      "bw": "Botsvana",
      "by": "Belarus",
      "bz": "Belize",
      "ca": "Kanada",
      "cc": "Cocos Adaları",
      "cd": "Kongo Demokratik Cumhuriyeti",
      "cf": "Orta Afrika Cumhuriyeti",
      "cg": "Kongo Cumhuriyeti",
      "ch": "İsviçre",
      "ci": "Fildişi Sahili",
      "ck": "Cook Adaları",
      "cl": "Şili",
      "cm": "Kamerun",
      "cn": "Çin",
      "co": "Kolombiya",
      "cr": "Kosta Rika",
      "cu": "Küba",
      "cv": "Yeşil Burun Adaları",
      "cw": "Curaçao",
      "cx": "Christmas Adası",
      "cy": "Kıbrıs Cumhuriyeti",
      "cz": "Çekya",
      "de": "Almanya",
      "dj": "Cibuti",
      "dk": "Danimarka",
      "dm": "Dominika",
      "do": "Dominik Cumhuriyeti",
      "dz": "Cezayir",
      "ec": "Ekvador",
      "ee": "Estonya",
      "eg": "Mısır",
      "er": "Eritre",
      "es": "İspanya",
      "et": "Etiyopya",
      "fi": "Finlandiya",
      "fj": "Fiji",
      "fk": "Falkland Adaları",
      "fm": "Mikronezya Federal Devletleri",
      "fo": "Faroe Adaları",
      "fr": "Fransa",
      "ga": "Gabon",
      "gb": "Birleşik Krallık",
      "gb-eng": "İngiltere",
      "gb-nir": "Kuzey İrlanda",
      "gb-sct": "İskoçya",
      "gb-wls": "Galler",
      "gd": "Grenada",
      "ge": "Gürcistan",
      "gf": "Fransız Guyanası",
      "gh": "Gana",
      "gi": "Cebelitarık",
      "gl": "Grönland",
      "gm": "Gambiya",
      "gn": "Gine",
      "gq": "Ekvator Ginesi",
      "gr": "Yunanistan",
      "gt": "Guatemala",
      "gu": "Guam",
      "gw": "Gine-Bissau",
      "gy": "Guyana",
      "hk": "Hong Kong",
      "hn": "Honduras",
      "hr": "Hırvatistan",
      "ht": "Haiti",
      "hu": "Macaristan",
      "id": "Endonezya",
      "ie": "İrlanda",
      "il": "İsrail",
      "im": "Man Adası",
      "in": "Hindistan",
      "io": "Britanya Hint Okyanusu Toprakları",
      "iq": "Irak",
      "ir": "İran",
      "is": "İzlanda",
      "it": "İtalya",
      "je": "Jersey",
      "jm": "Jamaika",
      "jo": "Ürdün",
      "jp": "Japonya",
      "ke": "Kenya",
      "kg": "Kırgızistan",
      "kh": "Kamboçya",
      "ki": "Kiribati",
      "km": "Komorlar",
      "kn": "Saint Kitts ve Nevis",
      "kp": "Kuzey Kore",
      "kr": "Güney Kore",
      "kw": "Kuveyt",
      "ky": "Cayman Adaları",
      "kz": "Kazakistan",
      "la": "Laos",
      "lb": "Lübnan",
      "lc": "Saint Lucia",
      "li": "Lihtenştayn",
      "lk": "Sri Lanka",
      "lr": "Liberya",
      "ls": "Lesotho",
      "lt": "Litvanya",
      "lu": "Lüksemburg",
      "lv": "Letonya",
      "ly": "Libya",
      "ma": "Fas",
      "mc": "Monako",
      "md": "Moldova",
      "me": "Karadağ",
      "mg": "Madagaskar",
      "mh": "Marshall Adaları",
      "mk": "Kuzey Makedonya",
      "ml": "Mali",
      "mm": "Myanmar",
      "mn": "Moğolistan",
      "mo": "Makao",
      "mp": "Kuzey Mariana Adaları",
      "mr": "Moritanya",
      "ms": "Montserrat",
      "mt": "Malta",
      "mu": "Mauritius",
      "mv": "Maldivler",
      "mw": "Malavi",
      "mx": "Meksika",
      "my": "Malezya",
      "mz": "Mozambik",
      "na": "Namibya",
      "nc": "Yeni Kaledonya",
      "ne": "Nijer",
      "nf": "Norfolk Adası",
      "ng": "Nijerya",
      "ni": "Nikaragua",
      "nl": "Hollanda Krallığı",
      "no": "Norveç",
      "np": "Nepal",
      "nr": "Nauru",
      "nu": "Niue",
      "nz": "Yeni Zelanda",
      "om": "Umman",
      "pa": "Panama",
      "pe": "Peru",
      "pf": "Fransız Polinezyası",
      "pg": "Papua Yeni Gine",
      "ph": "Filipinler",
      "pk": "Pakistan",
      "pl": "Polonya",
      "pn": "Pitcairn Adaları",
      "pr": "Porto Riko",
      "ps": "Filistin Devleti",
      "pt": "Portekiz",
      "pw": "Palau",
      "py": "Paraguay",
      "qa": "Katar",
      "ro": "Romanya",
      "rs": "Sırbistan",
      "ru": "Rusya",
      "rw": "Ruanda",
      "sa": "Suudi Arabistan",
      "sb": "Solomon Adaları",
      "sc": "Seyşeller",
      "sd": "Sudan",
      "se": "İsveç",
      "sg": "Singapur",
      "si": "Slovenya",
      "sj": "Svalbard ve Jan Mayen",
      "sk": "Slovakya",
      "sl": "Sierra Leone",
      "sm": "San Marino",
      "sn": "Senegal",
      "so": "Somali",
      "sr": "Surinam",
      "ss": "Güney Sudan",
      "st": "São Tomé ve Príncipe",
      "sv": "El Salvador",
      "sx": "Sint Maarten",
      "sy": "Suriye",
      "sz": "Esvatini",
      "tc": "Turks ve Caicos Adaları",
      "td": "Çad",
      "tf": "Fransız Güney ve Antarktika Toprakları",
      "tg": "Togo",
      "th": "Tayland",
      "tj": "Tacikistan",
      "tk": "Tokelau",
      "tl": "Doğu Timor",
      "tm": "Türkmenistan",
      "tn": "Tunus",
      "to": "Tonga",
      "tr": "Türkiye",
      "tt": "Trinidad ve Tobago",
      "tv": "Tuvalu",
      "tw": "Tayvan",
      "tz": "Tanzanya",
      "ua": "Ukrayna",
      "ug": "Uganda",
      "us": "Amerika Birleşik Devletleri",
      "uy": "Uruguay",
      "uz": "Özbekistan",
      "va": "Vatikan",
      "vc": "Saint Vincent ve Grenadinler",
      "ve": "Venezuela",
      "vg": "Britanya Virjin Adaları",
      "vn": "Vietnam",
      "vu": "Vanuatu",
      "ws": "Samoa",
      "xk": "Kosova",
      "ye": "Yemen",
      "yt": "Mayotte",
      "za": "Güney Afrika Cumhuriyeti",
      "zm": "Zambiya",
      "zw": "Zimbabve"
    ]
    
}
